remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: ""
    values:
      links:
        -
          title: Download
          url: https://github.com/vanjac/aodix-enhanced/releases
        -
          title: GitHub
          url: https://github.com/vanjac/aodix-enhanced
